# Generated by Django 4.2.15 on 2024-08-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_remove_productcomment_image_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=100, verbose_name='lastname')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('phone_number', models.PositiveIntegerField(max_length=15, verbose_name='phone')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('is_paid', models.BooleanField(default=False, verbose_name='ispaid')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product', verbose_name='product')),
            ],
        ),
    ]
