# Generated by Django 4.2.15 on 2024-08-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcomment_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='book',
            new_name='product',
        ),
    ]
