# Generated by Django 4.2.15 on 2024-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_book_productcomment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='slug_field',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
