# Generated by Django 4.2.15 on 2024-08-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcomment_slug_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='slug_field',
        ),
    ]
