# Generated by Django 4.2.15 on 2024-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcomment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_covers/'),
        ),
    ]
